#!/usr/bin/env python
"""Prove the raw-baseline configs differ from the validated references only in dataset/run fields.

Two comparisons, per seed:

  A. every setting's six placeholder configs (configs/1.5B-baseline-seed<S>/<setting>_seed<S>_<kind>.yaml)
     against raw_random's, after substituting the setting name: the text must be identical except for
     the `# template :` provenance comment line. This covers trunk and branch segments.
  B. each setting's ep1/ep2/ep3 config against the config.yaml of the released v2 Quality-Base checkpoint
     (wytro/KYS-1.5B-Rewritten-v2 rewrite-1p5b/seed<S>/quality_base/ep<N>/nanotron/config.yaml, pinned
     revision), key by key over every key the raw config sets. Keys that may differ, and why:
        general.run, checkpoints.checkpoints_path, checkpoints.resume_checkpoint_path,
        data_stages.0.data.dataset.dataset_folder, tokenizer.tokenizer_name_or_path   run / dataset / site paths
        parallelism.recompute_layer                                                    speed only (no math change)
        tokens.micro_batch_size, tokens.batch_accumulation_per_replica                 reported, see below
     micro_batch_size is reported, not waived: v2 Quality-Base seed 42 ran mbs 16 / accum 16, seeds 43/44
     mbs 32 / accum 8; the raw configs use mbs 32 / accum 8 (the grid's value in 53 of 54 runs).
     Keys present only in the v2 dump (nanotron fills defaults when it serializes) are listed separately.
  C. (--data-root, --tokenizer) each branch config with its placeholders filled is parsed by nanotron's own
     loader (nanotron.config.get_config_from_file) and re-serialized, then compared with the v2 dump over the
     union of keys: this checks that the defaults nanotron fills in are the ones v2 ran with. The parser needs
     <data_root>/<setting>/tokenized to exist with .ds.metadata (any tokenized corpus works as a stand-in:
     only the tokenizer string and vocab size are read).

    python tools/kys_raw/compare_configs.py --v2-dir <dir holding rewrite-1p5b/seed<S>/quality_base/...> --out <md>
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from registry import KINDS, SEEDS, SETTING_NAMES  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
V2_REVISION = 'b22c87333783945e1c655ae46886b7e842ee4203'
RUN_FIELDS = {'general.run', 'checkpoints.checkpoints_path', 'checkpoints.resume_checkpoint_path',
              'data_stages.0.data.dataset.dataset_folder', 'tokenizer.tokenizer_name_or_path'}
SPEED_FIELDS = {'parallelism.recompute_layer'}
BATCH_FIELDS = {'tokens.micro_batch_size', 'tokens.batch_accumulation_per_replica'}


def flat(d, pre=''):
    out = {}
    if isinstance(d, dict):
        for k, v in d.items():
            out.update(flat(v, f'{pre}{k}.'))
    elif isinstance(d, list) and d and isinstance(d[0], dict):
        for i, v in enumerate(d):
            out.update(flat(v, f'{pre}{i}.'))
    else:
        out[pre[:-1]] = d
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--v2-dir', type=Path, required=True)
    ap.add_argument('--out', type=Path, required=True)
    ap.add_argument('--data-root', help='for C: directory holding <setting>/tokenized for every setting')
    ap.add_argument('--tokenizer', help='for C: tokenizer directory named in the corpora\'s .ds.metadata')
    args = ap.parse_args()
    lines = ['# Raw-baseline config comparison', '',
             f'Generated by `tools/kys_raw/compare_configs.py`. Reference B: `wytro/KYS-1.5B-Rewritten-v2@{V2_REVISION[:12]}`.', '']
    fail = 0

    lines += ['## A. Every setting vs raw_random (all six segments, text after name substitution)', '',
              '| seed | setting | segments identical |', '|---|---|---|']
    for seed in SEEDS:
        d = REPO / 'configs' / f'1.5B-baseline-seed{seed}'
        for s in SETTING_NAMES:
            ok = 0
            for k in KINDS:
                a = (d / f'{s}_seed{seed}_{k}.yaml').read_text().replace(s, 'raw_random').splitlines()
                b = (d / f'raw_random_seed{seed}_{k}.yaml').read_text().splitlines()
                strip = lambda x: [ln for ln in x if not ln.startswith('# template :')]  # noqa: E731
                ok += strip(a) == strip(b)
            fail += ok != len(KINDS)
            lines.append(f'| {seed} | {s} | {ok}/{len(KINDS)} |')

    lines += ['', '## B. Branch segments vs the released v2 Quality-Base checkpoint config', '',
              '| seed | segment | settings | keys compared | equal | run/dataset/path keys | speed keys | batch keys (raw vs v2) | other differences |',
              '|---|---|---|---:|---:|---:|---:|---|---|']
    v2_only_keys = {}
    for seed in SEEDS:
        for n in (1, 2, 3):
            ref = flat(yaml.safe_load((args.v2_dir / f'rewrite-1p5b/seed{seed}/quality_base/ep{n}/nanotron/config.yaml').read_text()))
            rows = {}
            for s in SETTING_NAMES:
                cfg = flat(yaml.safe_load((REPO / 'configs' / f'1.5B-baseline-seed{seed}' / f'{s}_seed{seed}_ep{n}.yaml').read_text()))
                eq, run, speed, other, batch = 0, 0, 0, [], []
                for k, v in cfg.items():
                    if k not in ref:
                        other.append(f'{k} (absent in v2)')
                    elif ref[k] == v:
                        eq += 1
                    elif k in RUN_FIELDS:
                        run += 1
                    elif k in SPEED_FIELDS:
                        speed += 1
                    elif k in BATCH_FIELDS:
                        batch.append(f'{k.split(".")[1]} {v} vs {ref[k]}')
                    else:
                        other.append(f'{k}: {v!r} vs {ref[k]!r}')
                for k in ref.keys() - cfg.keys():
                    v2_only_keys.setdefault(k, set()).add(repr(ref[k]))
                rows.setdefault((len(cfg), eq, run, speed, '; '.join(batch) or '-', '; '.join(other) or 'none'), []).append(s)
                fail += bool(other)
            for (nk, eq, run, speed, batch, other), ss in rows.items():
                lines.append(f'| {seed} | ep{n} | {len(ss)} of {len(SETTING_NAMES)} | {nk} | {eq} | {run} | {speed} | {batch} | {other} |')
    lines += ['', '### Keys only in the v2 dump (nanotron serializes its defaults; the raw configs leave them to the same defaults)', '',
              '| key | v2 value(s) |', '|---|---|']
    for k in sorted(v2_only_keys):
        if k.startswith(('general.step', 'general.consumed_train_samples')):
            continue
        lines.append(f'| `{k}` | {", ".join(sorted(v2_only_keys[k]))} |')
    if args.data_root:
        import tempfile
        sys.path.insert(0, str(REPO / 'src'))
        from nanotron.config import get_config_from_file
        allowed = RUN_FIELDS | BATCH_FIELDS | {'data_stages.0.data.dataset.tokenizer_name', 'general.step',
                                               'general.consumed_train_samples'}
        lines += ['', '## C. nanotron-parsed branch configs vs the v2 dump (union of all serialized keys)', '',
                  '| seed | segment | settings | keys | differing outside run/path/batch/runtime fields |', '|---|---|---|---:|---|']
        for seed in SEEDS:
            for n in (1, 2, 3):
                ref = flat(yaml.safe_load((args.v2_dir / f'rewrite-1p5b/seed{seed}/quality_base/ep{n}/nanotron/config.yaml').read_text()))
                bad, nkeys = [], 0
                for s in SETTING_NAMES:
                    text = (REPO / 'configs' / f'1.5B-baseline-seed{seed}' / f'{s}_seed{seed}_ep{n}.yaml').read_text()
                    text = (text.replace('{{DATA_ROOT}}', args.data_root).replace('{{TOKENIZER_PATH}}', args.tokenizer)
                            .replace('{{CKPT_ROOT}}', '/ckpt').replace("'{{RECOMPUTE_LAYER}}'", 'false'))
                    with tempfile.TemporaryDirectory() as td:
                        (Path(td) / 'c.yaml').write_text(text)
                        get_config_from_file(str(Path(td) / 'c.yaml')).save_as_yaml(str(Path(td) / 'd.yaml'))
                        got = flat(yaml.safe_load((Path(td) / 'd.yaml').read_text()))
                    keys = set(got) | set(ref)
                    nkeys = len(keys)
                    bad += [f'{s}:{k}' for k in keys if got.get(k, '<absent>') != ref.get(k, '<absent>') and k not in allowed]
                fail += bool(bad)
                lines.append(f'| {seed} | ep{n} | {len(SETTING_NAMES)} | {nkeys} | {"; ".join(bad) or "none"} |')
    lines += ['', f'**Result: {"PASS" if not fail else f"FAIL ({fail})"}** — no difference outside the listed run/dataset/path, '
              'speed and batch keys.' if not fail else '']
    args.out.write_text('\n'.join(lines) + '\n')
    print('\n'.join(lines))
    sys.exit(1 if fail else 0)


if __name__ == '__main__':
    main()
