#!/usr/bin/env python
"""Write (and optionally run) the SLURM submission script for one seed of the raw baselines.

    python tools/kys_raw/plan_submit.py --cluster marc-cluster --seed 42 [--s-per-it 16.5] [--submit]

Reads the 24 filled configs in configs/1.5B-baseline-seed<S>/filled/ (tools/kys_raw/fill_placeholders.py)
and the cluster entry in deploy/clusters.yaml, re-runs tools/assert_invariants.py on each (placeholders,
batch, environment are checked; corpus and resume are checked by the launcher before every segment),
and writes configs/1.5B-baseline-seed<S>/filled/submit_seed<S>.sh containing:

  1. trunk seeding per setting: <ckpt_root>/seed<S>/<setting>/trunk/<setting>/seed<S>/0 <- the seed's
     init checkpoint, latest.txt = 0 (skipped when latest.txt already exists);
  2. 24 sbatch calls with the dependency chain, each job id captured for its dependents:
        trunk1 -> trunk2 -> trunk3          (afterok)
        trunk1 -> ep1, trunk2 -> ep2, trunk3 -> ep3

Every job runs deploy/slurm/kys_segment.sbatch, which is requeue-safe: a restarted trunk resumes from
its latest checkpoint through latest.txt, a restarted branch re-runs from its branch point, and a
segment whose final checkpoint exists exits 0. afterok holds across a requeue (same job id).

Nothing is submitted unless --submit is given; by default the script is only written and printed.
"""
from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
SBATCH = REPO / 'deploy' / 'slurm' / 'kys_segment.sbatch'
SETTINGS = ['raw_diversity_oriented', 'raw_disagreement_aware', 'raw_random', 'raw_rewire_inspired']
KINDS = ['trunk1', 'trunk2', 'trunk3', 'ep1', 'ep2', 'ep3']
DEPENDS = {'trunk1': None, 'trunk2': 'trunk1', 'trunk3': 'trunk2', 'ep1': 'trunk1', 'ep2': 'trunk2', 'ep3': 'trunk3'}
FIRST_STEP = {'trunk1': 0, 'trunk2': 4292, 'trunk3': 8583, 'ep1': 4292, 'ep2': 8583, 'ep3': 12875}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cluster', default='marc-cluster')
    ap.add_argument('--seed', type=int, required=True)
    ap.add_argument('--configs', type=Path, help='default: configs/1.5B-baseline-seed<S>/filled')
    ap.add_argument('--settings', default=','.join(SETTINGS))
    ap.add_argument('--s-per-it', type=float, help='measured seconds per optimizer step, for the wall-time table')
    ap.add_argument('--expected-mbs', type=int, help='forwarded to assert_invariants.py if mbs != 32')
    ap.add_argument('--submit', action='store_true')
    ap.add_argument('--profile', type=Path, default=REPO / 'deploy' / 'clusters.yaml')
    args = ap.parse_args()

    prof = yaml.safe_load(args.profile.read_text())
    c = prof['clusters'][args.cluster]
    sl = c.get('slurm') or {}
    for k in ('partition', 'gres', 'cpus_per_task', 'time'):
        if sl.get(k) is None:
            sys.exit(f'{args.cluster}.slurm.{k} is null in deploy/clusters.yaml')
    cfg_dir = args.configs or REPO / 'configs' / f'1.5B-baseline-seed{args.seed}' / 'filled'
    init_root = c.get('init_root')
    log_dir = Path((c.get('wandb') or {}).get('dir') or cfg_dir).parent / 'slurm_logs'
    exports = {'KYS_REPO': c.get('repo_dir'), 'KYS_ENV_ACTIVATE': c.get('env_activate'),
               'KYS_PYTHON_INCLUDE': c.get('python_include')}
    export_arg = ','.join(['ALL'] + [f'{k}={v}' for k, v in exports.items() if v])

    lines = ['#!/usr/bin/env bash', f'# Generated by tools/kys_raw/plan_submit.py --cluster {args.cluster} --seed {args.seed}',
             'set -euo pipefail', f'mkdir -p {shlex.quote(str(log_dir))}', '']
    rows = []
    for setting in args.settings.split(','):
        trunk_cfg = yaml.safe_load((cfg_dir / f'{setting}_seed{args.seed}_trunk1.yaml').read_text())
        trunk = Path(trunk_cfg['checkpoints']['checkpoints_path'])
        init = Path(init_root or '<init_root>') / f'_init_1.5B_seed{args.seed}' / '0'
        lines += [f'# ---- {setting} seed {args.seed}',
                  f'T={shlex.quote(str(trunk))}',
                  'if [[ ! -f "$T/latest.txt" ]]; then',
                  f'  mkdir -p "$T" && cp -a {shlex.quote(str(init))} "$T/0" && echo 0 > "$T/latest.txt"',
                  'fi']
        for kind in KINDS:
            name = f'{setting}_seed{args.seed}_{kind}'
            cfg = cfg_dir / f'{name}.yaml'
            chk = [sys.executable, REPO / 'tools/assert_invariants.py', '--config', cfg, '--skip-corpus', '--skip-env']
            if args.expected_mbs:
                chk += ['--expected-mbs', str(args.expected_mbs)]
            r = subprocess.run(chk, capture_output=True, text=True)
            if r.returncode:
                sys.exit(f'{cfg} fails assert_invariants.py:\n{r.stdout[-600:]}{r.stderr[-600:]}')
            steps = yaml.safe_load(cfg.read_text())['tokens']['train_steps'] - FIRST_STEP[kind]
            var = name.upper().replace('-', '_')
            opts = [f'--job-name=kys_{name}', f'--partition={sl["partition"]}', f'--gres={sl["gres"]}',
                    f'--nodes={sl.get("nodes") or 1}', f'--cpus-per-task={sl["cpus_per_task"]}', f'--time={sl["time"]}',
                    f'--output={log_dir}/%x.%j.log', f'--export={export_arg}']
            opts += [f'--account={sl["account"]}'] if sl.get('account') else []
            opts += [f'--qos={sl["qos"]}'] if sl.get('qos') else []
            dep = DEPENDS[kind]
            if dep:
                opts.append(f'--dependency=afterok:${{{f"{setting}_seed{args.seed}_{dep}".upper()}}}')
            lines.append(f'{var}=$(sbatch --parsable {" ".join(shlex.quote(o) if "$" not in o else o for o in opts)} '
                         f'{shlex.quote(str(SBATCH))} {shlex.quote(str(cfg))} | cut -d";" -f1)')
            lines.append(f'echo "{name}: ${var}"')
            est = f'{steps * args.s_per_it / 3600:.1f}' if args.s_per_it else '-'
            rows.append((name, steps, est, dep or '-'))
        lines.append('')

    out = cfg_dir / f'submit_seed{args.seed}.sh'
    out.write_text('\n'.join(lines) + '\n')
    out.chmod(0o755)
    print(f'{"job":42s} {"steps":>6s} {"est h":>6s} {"after":>7s}')
    for name, steps, est, dep in rows:
        print(f'{name:42s} {steps:6d} {est:>6s} {dep:>7s}')
    print(f'\nwrote {out} (all 24 configs passed assert_invariants.py)')
    if args.submit:
        subprocess.run(['bash', out], check=True)


if __name__ == '__main__':
    main()
