#!/usr/bin/env python
"""Render GLOBAL_TOP10B_SELECTION_REPORT.md from selection_report.json (+ tokenization/publication records).

    python tools/kys_raw/render_selection_report.py --report <selection>/selection_report.json \
        [--tokenized-dir <dir with tokenized_<setting>.json>] [--published <published.json>] \
        [--rerun-manifest <second selection_manifest.json>] [--scorer-audit <overlaps.json>] \
        [--export-verify <verify_export.json>] --out GLOBAL_TOP10B_SELECTION_REPORT.md

Every number comes from the JSON inputs; nothing is typed in by hand.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

NEW = ['raw_top10b_fineweb_edu', 'raw_top10b_modernbert', 'raw_top10b_consensus']
SETS = ['quality_base', *NEW]
SHORT = {'quality_base': 'QB (fastText)', 'raw_top10b_fineweb_edu': 'FW-Edu', 'raw_top10b_modernbert': 'ModernBERT',
         'raw_top10b_consensus': 'Consensus', 'fasttext_quality_base': 'QB (fastText)', 'validation_holdout_50k': 'validation holdout (50k)'}


def n(x):
    return f'{x:,}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--report', type=Path, required=True)
    ap.add_argument('--tokenized-dir', type=Path)
    ap.add_argument('--published', type=Path)
    ap.add_argument('--rerun-manifest', type=Path, help='selection_manifest.json of an independent rerun (e.g. other numpy)')
    ap.add_argument('--scorer-audit', type=Path, help='reports/scorer_training_audit/overlaps.json')
    ap.add_argument('--export-verify', type=Path, help='tools/kys_raw/verify_global_top10b.py output')
    ap.add_argument('--out', type=Path, required=True)
    a = ap.parse_args()
    R = json.loads(a.report.read_text())
    M = R['selection_manifest']
    L = ['# Global Top-10B selections — selection report', '',
         'Three anchor-free 1.5B baselines, each selecting its entire ~10B TRAIN-token corpus from the Quality-Base universe '
         'with one score, compared with the existing fastText Quality-Base. Generated by '
         '`tools/kys_raw/render_selection_report.py` from `selection_report.json` (`tools/kys_raw/report_global_top10b.py`) '
         'and `selection_manifest.json` (`tools/kys_raw/select_global_top10b.py`). These analyses describe the *data*; '
         'they say nothing about downstream performance.', '']

    u = M['universe']
    L += ['## 1. Definition', '',
          f'- **Scored pool:** `{M["scored_pool"]["repo"]}@{M["scored_pool"]["revision"][:8]}`, {n(M["scored_pool"]["rows"])} rows '
          '(the table every KYS selection ran over).',
          f'- **Eligible universe:** all rows minus the 50,000-doc validation holdout = **{n(u["eligible"])} docs, '
          f'{n(u["eligible_train_tokens"])} TRAIN tokens**. The holdout is '
          '`sort(default_rng(SeedSequence(42).spawn(8)[0]).choice(N, 50_000, replace=False))`, exactly as '
          '`projects/rewrite/04_select/select_10b.py`, with sorted-id sha256 '
          f'`{u["val_doc_ids_sha256"][:16]}…`. No other exclusion; in particular the 5M analysis sample is **not** excluded, '
          'as in the original. The scorer-training documents were already removed from the pool itself (§2b).',
          '- **TRAIN tokens:** `tokens-llama2 + 1`, i.e. Llama-2 length without special tokens, plus the one `</s>` '
          'datatrove appends.',
          '- **Scores.** Each is the pipeline\'s tie-aware global percentile, `rankdata(raw, "average") / 99,949,162`. '
          'The reference population is all scored rows, validation docs included; higher is better.',
          '  - `raw_top10b_fineweb_edu`: `fineweb-edu-ranking-v2`.',
          '  - `raw_top10b_modernbert`: `modernbert-ranking-v2`.',
          '  - `raw_top10b_consensus`: `q = ((ft + fw + mb) / 3.0).astype(float32)` over the three v2 percentiles, the '
          'same expression as `select_10b.py` / `select_s5.py`. Raw scores are not averaged. There is no variance term, '
          'floor, quota, domain restriction or rewriting.',
          '- **Order:** score descending (compared in float64). Ties are broken by '
          '`default_rng(SeedSequence(42).spawn(8)[1]).permutation(N)` ascending, i.e. `select_10b.order_desc`.',
          '- **Cutoff:** keep whole documents along the order until cumulative TRAIN tokens first reach '
          '10,000,000,000 (`select_10b.fill_to`, `searchsorted(..., "left")`). Overshoot is less than one document.',
          '- **No anchor:** the anchor is not added; a setting contains anchor documents only if its own score ranks them '
          'in (§4).',
          '- **Digest conventions:**']
    L += [f'  - `{k}`: {v}' for k, v in M['digest_conventions'].items()]
    L += ['']

    ref = M['reference']
    qb, g = ref['fasttext_quality_base_reconstruction'], ref['fasttext_global_top10b']
    L += ['## 2. The existing fastText Quality-Base under the same conventions', '',
          '- **Reconstruction.** The original Quality-Base is anchor (fastText prefix to 5e9) + the next 5e9 along the same '
          'order. Rebuilt with the rules above, it has:',
          f'  - {n(qb["docs"])} docs and {n(qb["train_tokens"])} TRAIN tokens (anchor {n(qb["shared_docs"])} / '
          f'{n(qb["shared_tokens"])}, block {n(qb["qb_docs"])} / {n(qb["qb_tokens"])});',
          f'  - doc-set sha256 `{qb["docset_sha256"]}`;',
          '  - the same digest as the published `wytro/Know-Your-Sources/quality_base/metadata.json` `doc_id_digest_sha256`;',
          f'  - an anchor part identical to the published anchor: **{qb.get("shared_top_equals_published_anchor")}**.',
          f'- **A single global fastText Top-10B** (`fill_to(order, 1e10)`) is {n(g["docs"])} docs and '
          f'{n(g["train_tokens"])} TRAIN tokens (overshoot {g["overshoot"]}). It is a subset of Quality-Base: '
          f'**{qb["global_top10b_subset_of_quality_base"]}**, differing by '
          f'**{qb["docs_in_quality_base_not_in_global_top10b"]} documents / {n(qb["train_tokens"] - g["train_tokens"])} tokens** '
          'at the tail.',
          '- **Why they differ.** The two-stage fill targets a cumulative 10,000,002,332 (5e9 + the anchor\'s 2,332 '
          'overshoot + 5e9) instead of 1e10.',
          '- **Consequence.** Quality-Base *is* the global fastText Top-10B up to those 3 tail documents (0.00002% of '
          'tokens), so it is the matching fastText comparator for the three new arms. Its data **order** differs: the v2 '
          'Quality-Base trained on the `10B-base-shuf42` shuffle of that set.', '']

    if a.scorer_audit:
        S = json.loads(a.scorer_audit.read_text())
        s50, s5, pp = S['set_50k'], S['set_5m'], S['pool_presence']
        o5 = S['overlaps']['sample5m_rederived']
        L += ['## 2b. Scorer-training data, the 5M analysis sample, and the source universe', '',
              'Audited from the scorer pipeline\'s own files and recomputed from document IDs; scripts and JSON in '
              '`configs/1.5B-baseline/reports/scorer_training_audit/` (nanotron repo).', '',
              '**What the ModernBERT score is trained on (verified).**',
              '- `modernbert` = a Ridge(α=1) head, trained by this project, on L2-normalised mean-pooled embeddings of the '
              'frozen external `nomic-ai/modernbert-embed-base` (`projects/rewrite/01_explore/score_modernbert.py`).',
              f'- Training rows: **50,427** Claude-Haiku-labelled documents ({n(s50["ridge_combined_dclm_rows"])} DCLM-RefinedWeb '
              '+ 218 OpenWebMath + 211 algebraic-stack). The stored `model_meta.json` records `n_train: 50427`; a refit on all '
              '50,427 rows reproduces the shipped coefficients (max |Δ| 2.1e-4), a refit on the 40,340 "train" split does not '
              '(0.56). So the "val" split was also fit; there was no separate calibration set.',
              f'- The {n(s50["selected_50k_for_claude_rows"])} DCLM documents picked for labelling (of which '
              f'{n(s50["scored_50k_final_rows"])} were scored and used) were drawn from the raw 100M pool, seed 42.',
              f'- **All of them were removed from the pool** before any scoring or selection: the 50,838 rows removed by '
              '`00_TMP/merge_remove_50k.py` are every row whose first 4,000 characters (sha1) match a labelled document '
              f'({n(s50["sel50k_in_removed"])} / 50,000 picks and {n(s50["ridge_dclm_in_removed"])} / '
              f'{n(s50["ridge_combined_dclm_rows"])} training documents are in the removed set; '
              f'{s50["removed_not_in_sel50k_(pool_duplicates_by_prefix)"]} further rows are prefix-duplicates). '
              f'Present in the published pool: **{pp["ridge_dclm_present_in_pool"]}** training documents, so **0** in the '
              'validation holdout, in any selection and in any corpus.',
              '- Not checked: near-duplicates whose first 4,000 characters differ; any overlap with the external embedder\'s '
              'own pretraining data (it only affects frozen features).', '',
              '**The ~5M analysis sample (verified).**',
              '- Drawn by `ppl_quality/sampling_5m/sample_5m.py`: `sort(default_rng(42).choice(100_000_000, 5_000_000))` '
              'over the raw pool. Re-derived here; the re-derivation matches the sample\'s URLs (1,000,000 / 1,000,000 '
              'checked in two shards) and the independently built exclusion table (all 5,000,000 positions).',
              '- Used for score/topic analysis (fastText, FineWeb-Edu, perplexity, an earlier analysis-only Ridge, Luxical '
              'clusters). **No code trains, validates or calibrates the production ModernBERT head on it**; the embedder '
              'card\'s "5M sample" refers to Nomic\'s own contrastive data, not this one.',
              f'- It was **not removed**: {n(s5["rederived_5m_surviving_in_pool"])} of its documents are in the published pool '
              f'({n(s5["exclusion_5m_basic_surviving"])} counting duplicate crawl copies, the figure the 3B plan quotes). The '
              'original 1.5B selection (`select_10b.py` l.202-205) excluded only the validation holdout; so did every later '
              'selection. These baselines therefore keep it, **for comparability with Quality-Base**; no new exclusion is '
              'introduced.', '',
              '| set | docs | 5M-sample docs inside | doc share | TRAIN-token share | expected at random | enrichment |',
              '|---|---:|---:|---:|---:|---:|---:|']
        for k in ['fasttext_quality_base', 'raw_top10b_fineweb_edu', 'raw_top10b_modernbert', 'raw_top10b_consensus',
                  'validation_holdout_50k']:
            v = o5[k]
            L.append(f'| {SHORT.get(k, k)} | {n(v["target_docs"])} | {n(v["overlap_docs"])} | {100 * v["overlap_doc_share"]:.3f}% | '
                     f'{100 * v["overlap_token_share"]:.3f}% | {n(round(v["expected_docs_if_random"]))} | {v["enrichment_docs"]:.3f} |')
        L += ['', '- Every selection holds the 5M sample at its pool rate (5.00%), with no enrichment: none of the scores '
              'prefers these documents. Their presence is not scorer-training leakage (the head never saw them).',
              '- **Evaluation contamination is a different question and was not tested.** No decontamination against '
              'ARC, HellaSwag, PIQA, SIQA, OpenBookQA, CommonsenseQA or MMLU was found for the scorer data or the pool; '
              'this applies equally to Quality-Base and every arm.',
              '- **Optional sensitivity experiment (not done, not part of the primary grid):** rerun the same three rules '
              'on the universe minus the 5M sample. Given 5.00% inclusion with enrichment 1.00, it would change about 5% '
              'of each corpus and would no longer be comparable with Quality-Base unless Quality-Base were rebuilt the '
              'same way.', '']

    L += ['## 3. Selected sets', '',
          '| setting | docs | TRAIN tokens | overshoot | boundary score | boundary doc (TRAIN tokens) | tie cluster at boundary: selected / eligible | next doc score |',
          '|---|---:|---:|---:|---:|---:|---:|---:|']
    for s in NEW:
        v = M['settings'][s]
        L.append(f'| `{s}` | {n(v["docs"])} | {n(v["train_tokens"])} | {n(v["overshoot"])} | {v["boundary_score"]:.9f} | '
                 f'{v["boundary_doc_id"]} ({n(v["boundary_doc_train_tokens"])}) | {n(v["boundary_tie_cluster_selected"])} / '
                 f'{n(v["boundary_tie_cluster_total"])} | {v["next_doc_score"]:.9f} |')
    L += ['', '- FineWeb-Edu has only 1,449 distinct raw scores. Its boundary sits inside a tie cluster of '
          f'{n(M["settings"]["raw_top10b_fineweb_edu"]["boundary_tie_cluster_total"])} documents, and the seeded tie '
          'permutation decides which ones enter. That is deterministic, and the same rule the original pipeline used.', '',
          '| setting | selection_order_sha256 | docset_sha256 | orig_docset_sha256 |', '|---|---|---|---|']
    for s in NEW:
        v = M['settings'][s]
        L.append(f'| `{s}` | `{v["selection_order_sha256"]}` | `{v["docset_sha256"]}` | `{v["orig_docset_sha256"]}` |')
    rr = M['deterministic_rerun_identical']
    L += ['', f'**Deterministic rerun.** A full second selection from scratch in the same process is identical: {all(rr.values())} ({rr}).']
    if a.rerun_manifest:
        o = json.loads(a.rerun_manifest.read_text())
        same = o['settings'] == M['settings'] and o['reference'] == M['reference']
        L.append(f'An independent run in a different environment (numpy 1.26.4 vs 2.0.2) gives identical counts, boundaries and digests: **{same}**.')
    L += ['']

    pv = R['percentile_verification']
    L += ['## 4. Percentile verification (consensus uses the correct percentiles)', '',
          'Each stored `*-ranking-v2` column was recomputed from its raw score column over all rows, as '
          '`scipy.stats.rankdata(raw.astype(float64), "average") / 99,949,162` cast to float32 (`00_TMP/clean_v2_ranks.py`).', '',
          '| column | rows equal | mismatches | max abs diff | higher raw ⇒ higher pct | distinct raw values | min / max stored |',
          '|---|---:|---:|---:|---|---:|---|']
    for k, v in pv['per_scorer'].items():
        L.append(f'| `{v["column"]}` | {n(v["exact_equal"])} | {v["mismatches"]} | {v["max_abs_diff"]} | {v["direction_higher_raw_higher_pct"]} | '
                 f'{n(v["distinct_raw"])} | {v["stored_min"]:.6g} / {v["stored_max"]:.6g} |')
    L += ['', f'- **Reference population:** {pv["reference_population"]}.',
          '- **Missing scores:** none; zero nulls in every raw, percentile, token and topic column.',
          f'- q from the recomputed percentiles equals q from the stored columns: **{pv["consensus_q_from_recomputed_equals_stored"]}**.',
          '- The consensus selection re-derived from the recomputed percentiles is identical: '
          f'**{pv["consensus_selection_from_recomputed_percentiles_identical"]}**.', '']

    L += ['## 5. Overlap', '',
          'Coverage of A by B = |A ∩ B| / |A|. Token-weighted = TRAIN tokens of A ∩ B / TRAIN tokens of A. Jaccard is on '
          'documents.', '',
          '| A | B | A ∩ B docs | A ∩ B TRAIN tokens | A covered by B (docs / tokens) | B covered by A (docs / tokens) | Jaccard |',
          '|---|---|---:|---:|---:|---:|---:|']
    for k, v in R['pairwise_overlap'].items():
        x, y = k.split('|')
        L.append(f'| {SHORT[x]} | {SHORT[y]} | {n(v["intersection_docs"])} | {n(v["intersection_train_tokens"])} | '
                 f'{100 * v["cov_a_by_b_docs"]:.2f}% / {100 * v["cov_a_by_b_tokens"]:.2f}% | '
                 f'{100 * v["cov_b_by_a_docs"]:.2f}% / {100 * v["cov_b_by_a_tokens"]:.2f}% | {v["jaccard"]:.4f} |')
    f4 = R['four_way']
    L += ['', f'- **In all four sets:** {n(f4["intersection_docs"])} docs / {n(f4["intersection_train_tokens"])} TRAIN tokens.',
          f'- **Union:** {n(f4["union_docs"])} docs / {n(f4["union_train_tokens"])} TRAIN tokens.', '',
          '| set | docs | TRAIN tokens | anchor docs inside | anchor share of tokens |', '|---|---:|---:|---:|---:|']
    for s in SETS:
        v = R['sets'][s]
        L.append(f'| {SHORT[s]} | {n(v["docs"])} | {n(v["train_tokens"])} | {n(v["anchor_docs_inside"])} | {100 * v["anchor_share_of_tokens"]:.2f}% |')
    L += ['']

    T = R['topics']
    L += ['## 6. Topic distributions (24 WebOrganizer labels)', '',
          'Shares in percent, TRAIN-token weighted.', '',
          '- TV = ½ Σ|p − r|.',
          '- JS = Jensen–Shannon divergence in bits (log base 2; 0 = identical, 1 = disjoint).',
          '- Both are measured against the eligible universe.', '',
          '| topic | eligible | ' + ' | '.join(SHORT[s] for s in SETS) + ' |', '|---|---:|' + '---:|' * len(SETS)]
    for i, lab in enumerate(T['labels']):
        L.append(f'| {lab} | {100 * T["eligible_universe"]["token_weighted"][i]:.2f} | ' +
                 ' | '.join(f'{100 * T[s]["token_weighted"][i]:.2f}' for s in SETS) + ' |')
    L += ['', '| set | TV (token-weighted) | JS bits (token-weighted) | TV (doc-weighted) | JS bits (doc-weighted) |', '|---|---:|---:|---:|---:|']
    for s in SETS:
        t, d = T[s]['vs_eligible_token_weighted'], T[s]['vs_eligible_doc_weighted']
        L.append(f'| {SHORT[s]} | {t["tv"]:.4f} | {t["js_bits"]:.4f} | {d["tv"]:.4f} | {d["js_bits"]:.4f} |')
    L += ['']

    P = R['profiles']
    L += ['## 7. Score and length profiles', '',
          '| set | mean ft / fw / mb pct | min ft / fw / mb pct | mean q | min q | mean / median TRAIN tokens per doc |', '|---|---|---|---:|---:|---|']
    for s in ['eligible_universe', *SETS]:
        v = P[s]
        L.append(f'| {SHORT.get(s, "eligible universe")} | {v["mean_ft_v2"]:.3f} / {v["mean_fw_v2"]:.3f} / {v["mean_mb_v2"]:.3f} | '
                 f'{v["min_ft_v2"]:.3f} / {v["min_fw_v2"]:.3f} / {v["min_mb_v2"]:.3f} | {v["mean_q"]:.3f} | {v["min_q"]:.3f} | '
                 f'{v["mean_train_tokens"]:.0f} / {v["median_train_tokens"]:.0f} |')
    po = R['pairwise_overlap'].values()
    dmin = min(min(v['cov_a_by_b_docs'], v['cov_b_by_a_docs']) for v in po)
    dmax = max(max(v['cov_a_by_b_docs'], v['cov_b_by_a_docs']) for v in po)
    tmin = min(min(v['cov_a_by_b_tokens'], v['cov_b_by_a_tokens']) for v in po)
    tmax = max(max(v['cov_a_by_b_tokens'], v['cov_b_by_a_tokens']) for v in po)
    L += ['', '**What these arms compare.**',
          '- Each new arm vs Quality-Base asks which single score, used to pick the whole 10B, gives the better corpus under '
          'identical training.',
          '- None of them involves rewriting, so none of them isolates a rewriting effect.',
          f'- Pairwise, any one set covers {100 * dmin:.0f}–{100 * dmax:.0f}% of another\'s documents '
          f'({100 * tmin:.0f}–{100 * tmax:.0f}% of its tokens; §5), so differences between arms come mostly from the '
          'non-shared part.', '']

    if a.export_verify:
        V = json.loads(a.export_verify.read_text())
        L += ['## 7b. Materialized corpora (independent check, `tools/kys_raw/verify_global_top10b.py`)', '',
              'Raw text read from the 100M raw pool by `orig_doc_id` (no rewriting, no transformation), shuffled once '
              '(`pp_io.bucketed_shuffle`, seed 42), exported to 16 contiguous files in that order.', '',
              '| setting | rows | TRAIN tokens | doc set == selection | duplicates | order == shuffle | file_order_sha256 | texts byte-equal to pool (sampled) | ok |',
              '|---|---:|---:|---|---:|---|---|---|---|']
        for s in NEW:
            v = V[s]
            t = v['text_sample']
            L.append(f'| `{s}` | {n(v["rows"])} | {n(v["train_tokens"])} | {v["docset_sha256"] == M["settings"][s]["docset_sha256"]} | '
                     f'{v["duplicate_doc_ids"]} | {v["order_equals_assembled_shuffle"]} | `{v["file_order_sha256"][:16]}…` | '
                     f'{n(t["rows_checked"] - t["mismatches"])} / {n(t["rows_checked"])} | {v["ok"]} |')
        L += ['', '- At assembly every document was re-tokenized and its length matched `tokens-llama2` exactly (0 mismatches).', '']
    if a.tokenized_dir:
        L += ['## 8. Tokenization check (consumer script, the three new settings)', '',
              '`tools/kys_raw/tokenize_raw_text.sh` was run unchanged on a local data root holding the published manifest, '
              'the tokenizer files and the 16 parquet files per setting. The script first checks every sha256. It then runs '
              'datatrove 0.5.0 with 16 tasks, `</s>` per document and no shuffling, applies `fix_ds_metadata.py`, and '
              'requires the total to equal `expected_total_tokens`.', '',
              '| setting | shards | datatrove total tokens | expected_total_tokens | equal | .ds bytes |', '|---|---:|---:|---:|---|---:|']
        for p in sorted(a.tokenized_dir.glob('tokenized_*.json')):
            v = json.loads(p.read_text())
            L.append(f'| `{v["setting"]}` | {v["shards"]} | {n(v["datatrove_total_tokens"])} | {n(v["expected_total_tokens"])} | '
                     f'{v["datatrove_total_tokens"] == v["expected_total_tokens"]} | {n(sum(v["ds_bytes"].values()))} |')
        L += ['']
    if a.published:
        p = json.loads(a.published.read_text())
        L += ['## 9. Publication', '',
              f'- **Repo and revision:** `{p["repo"]}` at revision `{p["revision"]}`.',
              f'- **Checksums:** {p["files_checked"]} uploaded data files (parquet and selection arrays) checked against the Hub\'s LFS sha256 and '
              f'size; mismatches: {p["lfs_sha256_mismatches"] or "none"}.',
              f'- **Manifest:** `manifest.json` downloaded back equals the local one: {p["manifest_roundtrip_equal"]}.',
              f'- **Generation code:** `imHuicongZhang/nanotron@{p["code_commit"]}`.', '']
    a.out.write_text('\n'.join(L) + '\n')
    print(f'wrote {a.out}')


if __name__ == '__main__':
    main()
